# Generated by Django 5.1.6 on 2025-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('automatic', 'Automatic Upload'), ('api', 'API Upload')], default='manual', max_length=20),
        ),
    ]
