# Generated by Django 5.1.6 on 2025-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_uploadedfile_upload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('automatic', 'Automatic Upload'), ('api', 'API Upload'), ('resume', 'Resume Upload')], default='manual', max_length=20),
        ),
    ]
